# Documentation: https://roots.io/trellis/docs/local-development-setup/
# `wordpress_sites` options: https://roots.io/trellis/docs/wordpress-sites
# Define accompanying passwords/secrets in group_vars/development/vault.yml

wordpress_sites:
  rampartls.com:
    site_hosts:
      - canonical: rampartls.dev
        redirects:
          - www.rampartls.dev
    local_path: ../bedrock # path targeting local Bedrock site directory (relative to Ansible root)
    admin_email: nic@ghettifish.com
    multisite:
      enabled: false
    ssl:
      enabled: false
      provider: self-signed
    cache:
      enabled: false
