# Documentation: https://roots.io/trellis/docs/remote-server-setup/
# `wordpress_sites` options: https://roots.io/trellis/docs/wordpress-sites
# Define accompanying passwords/secrets in group_vars/production/vault.yml

wordpress_sites:
  rampartls.ghet.co:
    site_hosts:
      - canonical: rampartls.ghet.co
        redirects:
          - www.rampartsls.ghet.co
    local_path: ../site # path targeting local Bedrock site directory (relative to Ansible root)
    repo: git@github.com:nicbovee/rampartls.ghet.co.git
    repo_subtree_path: site # relative path to your Bedrock/WP directory in your repo
    branch: master
    multisite:
      enabled: false
    ssl:
      enabled: true
      provider: letsencrypt
    cache:
      enabled: true
