# Documentation: https://roots.io/trellis/docs/remote-server-setup/
# `wordpress_sites` options: https://roots.io/trellis/docs/wordpress-sites
# Define accompanying passwords/secrets in group_vars/production/vault.yml

wordpress_sites:
  rampartls.ghet.co:
    site_hosts:
      - canonical: ramp.ghet.co
        redirects:
          - www.ramp.ghet.co
    local_path: ../bedrock # path targeting local Bedrock site directory (relative to Ansible root)
    repo: git@github.com:nicbovee/rampartls.ghet.co.git
    repo_subtree_path: bedrock
    branch: master
    multisite:
      enabled: false
    ssl:
      enabled: true
      provider: letsencrypt
    cache:
      enabled: true
